name: Docker image to gcp

on:
  push:
    branches:
      - main 
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      env:
        IMAGE_NAME: gcr.io/YOUR_PROJECT_ID/${{ github.repository }}:${{ github.sha }}
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Save image name for later jobs
      run: echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

  update-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Update Helm chart with new image
      env:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
      run: |
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
        helm upgrade --install $serverName stable/$chartName --set image.repository=gcr.io/YOUR_PROJECT_ID/${{ github.repository }} --set image.tag=${{ github.sha }}

    - name: Deploy to Kubernetes using Helm
      env:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
      run: |
        helm upgrade --install $serverName stable/$chartName --values ./path/to/your/values.yaml

   
